versions: "3"

services:
  db:
    image: postgres
    # below allow container to restart whenever it stops
    restart: always
    env_file:
      - ./env/template.env
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
     - ./env/template.env
    ports:
     - 5432:5432
    depends_on:
      - db
  # if use redis
  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  flaskservice:
    build: ./api
    # image: 
    ports: 
      - 5000:5000
    env_file:
      - ./env/template.env
    depends_on:
      - db
      - pgadmin
      # - redis
  
    
    
