TEMP_FLASK_APP=dspcalcservice
TEMP_FLASK_ENV=development
TEMP_DATABASE_HOST=localhost
TEMP_DATABASE_PORT=5432
TEMP_DATABASE_USER=user
TEMP_DATABASE_PASSWORD=0000

# if use redis
# QUEUE_TYPE=redis
# REDIS_HOST=redis
# REDOS_PORT=6379
# REDIS_DB=0